### ISSUE TITLE
Multi component used in single form. Only first one can show the calendar

### ISSUE THREAD

**Issue by kelvinliuhk** [jrainlau/vue-flatpickr#1]
Thank you for your component.

My problem is, If my single form use more than one component, only the first one is work. others calendar cannot be show up.

I found your  input type id="vue-flatpickr" is fixed value. I think this maybe the cause.

I try to update 'VueFlatpickr-en.vue' as below, to support custom id name, passing props from parent, but not yet work.  Please help.

```
<template>
  <input type="text" id="{{ oid }}">
</template>

<script>
import Flatpickr from './assets/flatpickr-en.js'

export default {
  props: {
    oid: {
      type: String,
      default: '#vue-flatpickr'
    },
    options: {
      type: Object
    }
  },
  watch: {
    options: {
      handler() {
        this.newFlatpickr()
      },
      deep: true
    }
  },
  ready() {
    // new Flatpickr(document.querySelector('#vue-flatpickr'), this.options)
    new Flatpickr(document.querySelector(this.oid), this.options)
  },
  mounted() {
    // new Flatpickr(document.querySelector('#vue-flatpickr'), this.options)
    new Flatpickr(document.querySelector(this.oid), this.options)
  }
}
</script>

```

**Comment by jrainlau** [comment]
Thanks for your issue, and I've fixed this bug by using random id inside the component, the Flatpickr instance will select the correct random id automatically.

Enjoy it!

**Comment by jrainlau** [comment]
Thanks for your issue, and I've fixed this bug by using random id inside the component, the Flatpickr instance will select the correct random id automatically.

Enjoy it!
