### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by spademan** [jrainlau/vue-flatpickr#2]
1.双向绑定不起作用
2.选择时分秒后没有自动关闭

**Comment by jrainlau** [comment]
1. 在线体验地址所使用的就是双向绑定，你选择了时间以后`The date you pick is: `后面的内容就是通过双向绑定获取的。
2. 需要点击日历外部才可关闭。

**Comment by spademan** [comment]
我用了vue2 双向绑定不起作用，不过也有可能和我的代码写法有关 暂时没找到原因
日历的话可以优化一下就好了
