### ISSUE TITLE
webpack loading issue

### ISSUE THREAD

**Issue by andreliem** [jrainlau/vue-flatpickr#21]
With the latest update which refactored the code to import `vue-flatpickr-base` from the default file, webpack is now giving me a resolution error:

```
Module not found: Error: Can't resolve './vue-flatpickr-base' in '/.../node_modules/vue-flatpickr'
```

I'm not sure if this is specific to `vue-flatpickr` as I can manually patch it by adding in the `.vue` extension in the import path. 

Any tips or suggestions on what I can configure on webpack to make this work would be appreciated.

**Comment by jrainlau** [comment]
I am working on the newest version of `VueFlatpickr`, and it will be released today.

**Comment by andreliem** [comment]
Thanks @jrainlau.
