### ISSUE TITLE
Flatpickr is not defined

### ISSUE THREAD

**Issue by andreliem** [jrainlau/vue-flatpickr#24]
I followed the readme instructions and keep getting `Flatpickr is not defined`.

Looks like I have it setup properly

Bootstrap file contains
```
import Vue from 'vue'
import VueFlatpickr from 'vue-flatpickr';
Vue.use(VueFlatpickr);
```

Child component has this:

```
<template>
<Flatpickr />
</template>

<script>
        components: {
            Flatpickr
        },
</script>
```

I've tried importing directly in the component as well but that's not working either... 

Any ideas?

**Comment by andreliem** [comment]
Oh my bad, looks like taking it out of the `components` field fixes that issue.

**Comment by jrainlau** [comment]
Once you set `Vue.use(VueFlatpickr)`, it means `Vue-Flatpickr` has registed globally. No need to define it in `components: {}`, just use `<Flatpickr />` directly.
