### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by arlando** [jrainlau/vue-flatpickr#25]
Hi @jrainlau thank you for coding this. There is currently no testing.

Are there plans to add testing? Anyway I can help? Thanks.

**Comment by jrainlau** [comment]
'Cause I can only maintain `Vue-Flatpickr` in my spare time, and we are getting closer to the end of the Chinese new year, there are lots of works to do, I'm afraid that I don't have enough time to add unit tests to  `Vue-Flatpickr`. If possible, it would be grateful for recieving a PR contains unit tests.
Have a nice day!

**Comment by arlando** [comment]
Thanks. I will try to help... have a Happy New Year! 💯
