### ISSUE TITLE
How to re-render the picker after updating props options

### ISSUE THREAD

**Issue by MaxZGYL** [jrainlau/vue-flatpickr#29]
```html
<Flatpickr :options="fpOptions"/>
```
```javascript
data(){
      return {
        fpOptions: {
          maxDate: "2017-6-20",
          }
    },
```
How do get the picker re-render after i update `maxDate`'s value?

**Comment by jrainlau** [comment]
I've fix the bug and you should update `Vue-Flatpickr` to the latest version. In this version, it wouldn't re-render itself but would update the options from props automatically.
