### ISSUE TITLE
Multiple and Range modes not working with v-model

### ISSUE THREAD

**Issue by danhassan** [jrainlau/vue-flatpickr#30]
When trying to use v-model in either of the modes other than 'single' the component stops working and reads "undefined: NaN". 

![image](https://cloud.githubusercontent.com/assets/8194883/21906765/9ecd4d0a-d8da-11e6-951d-13881735fe6b.png)

**Comment by jrainlau** [comment]
I've fixed this bug in the latest verstion 2.2.7, thanks for telling me about this.
