### ISSUE TITLE
Update local data using the input event works only once

### ISSUE THREAD

**Issue by axlf** [jrainlau/vue-flatpickr#31]
I'm using the flatpickr in a component. I want to update a local var catching the input event.

But somehow it works only the first time I select a date. In the vue devtools I see that input events are fired every time I select a date, but my listener isn't called more than once.

Template:
```
<flatpickr @input="catchInputEvent"></flatpickr>
```

In the Component:
```
mehtods: {
    catchInputEvent: function(value) {
        console.log('new value:'. + value);
    }
}
```

I see the console message only the first time.

What am I missing?

**Comment by jrainlau** [comment]
you should use `input.native` instead.

**Comment by jrainlau** [comment]
This is a bug and I've fixed it in the latest version.
