### ISSUE TITLE
v-model not working

### ISSUE THREAD

**Issue by Pandazaur** [jrainlau/vue-flatpickr#4]
Hello,

There is a problem with the `v-model` of the datepicker. I can set a value using `v-model` but when I change the value the data is not updated.

Here is jsfiddle: [https://jsfiddle.net/da77r6tq/](https://jsfiddle.net/da77r6tq/)

I'm using Vue.js 2.0 with Webpack

**Comment by jrainlau** [comment]
Thx for your feedback. `vue-flatpickr` was built by `vue.js 1.x`, and havn't been update yet. I'll update it by using `vue.js 2` soon.

**Comment by jrainlau** [comment]
Now you can use the 2.0 version from the default branch `2.0`. Enjoy it!
