### ISSUE TITLE
TypeError: Cannot read property 'onValueUpdate' of undefined

### ISSUE THREAD

**Issue by AchillesKal** [jrainlau/vue-flatpickr#43]
I follow the instructions and I get "TypeError: Cannot read property 'onValueUpdate' of undefined"

"vue": "^2.1.0",
"vue-flatpickr": "^2.2.9"

**Comment by mark-vesterskov** [comment]
+1 - I've got the same issue with a blank install.

"vue": "^2.1.0",
"vue-flatpickr": "^2.2.9"

**Comment by mark-vesterskov** [comment]
Initializing the element with `:options="{onValueUpdate : null}"` seems to fix the issue.

The error seems to arise from the attribute onValueUpdate not being set in the options by default, as the options are just initialized to an empty object.

https://github.com/jrainlau/vue-flatpickr/blob/2.0/src/components/vue-flatpickr.vue#L43
