### ISSUE TITLE
model updates not being reflected

### ISSUE THREAD

**Issue by cspeer** [jrainlau/vue-flatpickr#49]
Hi there,

I'm running on the lastest version. Everything is working fine except when I set `altInput = true`
my updates to the assigned model don't get reflected in the datepicker or the input field itself.
Suppose I'm loading data from an API which is written back to the component's data object upon arrival it would have zero effect on vue-flatpickr.

Chris

**Comment by jacobmischka** [comment]
PR is in #34, and previously (and since reverted, I'm assuming accidentally) in #27.

In the meantime I'm using my fork at [`@jacobmischka/vue-flatpickr`](https://www.npmjs.com/package/@jacobmischka/vue-flatpickr), should work for you in the meantime until this package is updated.

**Comment by cspeer** [comment]
Thank you Jacob! I sure came across the tickets you mentioned but I was a little confused whether they actually refer to the same problem. 
Thanks for your swift support!
