### ISSUE TITLE
multiple dates and range mode

### ISSUE THREAD

**Issue by YurkaKliuiev** [jrainlau/vue-flatpickr#5]
Hi,
Could you add multiple dates and range mode in the next update?
thanks

**Comment by jrainlau** [comment]
Hello~
`Vue-Flatpickr` bases on the [flatpickr](https://github.com/chmln/flatpickr), and `Vue-Flatpickr` would be sync with it, so, you could open an issue over there.
Thank you!

**Comment by YurkaKliuiev** [comment]
Hello,
yeah, I know but flatpickr has multiple dates and range mode, that's why I'm asking
https://chmln.github.io/flatpickr/
thanks for your work

**Comment by jrainlau** [comment]
Awesome! I'll do it soon~

**Comment by jrainlau** [comment]
@YurkaKliuiev Now you can use the 2.0 version from the default branch `2.0`, which contains all the features as the official one, and work for `VueJS 2.0`. Enjoy it!

**Comment by lukpep** [comment]
@jrainlau 
Does vue 1.x version will receive range mode?
