### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onValueUpdate' of undefined  

### ISSUE THREAD

**Issue by mesqueeb** [jrainlau/vue-flatpickr#52]
I get this issue:

> Uncaught TypeError: Cannot read property 'onValueUpdate' of undefined

**Comment by mark-vesterskov** [comment]
#43

**Comment by hultberg** [comment]
@mark-vesterskov Sadly, I'm unable to determine that your PR has been released definitely because there are no tags for releases. However, your workaround does work in my project where I encountered this error.

**Comment by mesqueeb** [comment]
@mark-vesterskov 
Solved because of your answer! You're the best!
