### ISSUE TITLE
Include translation

### ISSUE THREAD

**Issue by SergeyMiracle** [jrainlau/vue-flatpickr#7]
Is it possible or not to include some translations?

And hello from 济南 to you 😄

**Comment by jrainlau** [comment]
The officail `Flatpickr` supports `i10n`, you could find them [here](https://github.com/chmln/flatpickr/tree/gh-pages/src). All you need to do is to overwrite the `vue-flatpickr/assets/flatpickr.js` by one of them.

**Comment by SergeyMiracle** [comment]
Ok i see thx.
